backend:
  name: git-gateway
  branch: master

media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: djimngd9g
    api_key: 354114999119245

collections:
  - name: "company"
    label: "Company"
    editor:
      preview: false
    files:
      - label: "List"
        name: "about"
        file: "src/__data__/company/list.json"
        fields:
          - name: companies
            label: Companies
            widget: list
            collapsed: false
            fields:
            - {label: "Id", name: "id", widget: "number"}
            - {label: "Slug", name: "slug", widget: "string"}
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Description", name: "description", widget: "text"}
            - {label: "Start", name: "start", widget: "string"}
            - {label: "End", name: "end", widget: "string"}
            - {label: "Job Title", name: "jobTitle", widget: "string"}
            - {label: "Job Description", name: "jobDescription", widget: "text"}

