backend:
  name: git-gateway
  branch: master

media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: djimngd9g
    api_key: 354114999119245

collections:
  - name: "company"
    label: "Company"
    editor:
      preview: false
    files:
      - label: "List"
        name: "about"
        file: "src/__data__/company/list.json"
        fields:
          - name: "companies"
            label: "Companies"
            widget: list
            collapsed: false
            identifier_field: "title"
            fields:
            - {label: "Id", name: "id", widget: "number"}
            - {label: "Slug", name: "slug", widget: "string"}
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Description", name: "description", widget: "text"}
            - {label: "Start", name: "start", widget: "string"}
            - {label: "End", name: "end", widget: "string"}
            - {label: "Job Title", name: "jobTitle", widget: "string"}
            - {label: "Job Description", name: "jobDescription", widget: "text"}

  - name: "project"
    label: "Project"
    editor:
      preview: false
    folder: "src/__data__/project"
    create: true
    extension: "json"
    format: "json"
    slug: "{{slug}}"
    identifier_field: "{{slug}} {{title}}"
    fields:
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Company Slug", name: "companySlug", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Type", name: "type", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Country", name: "country", widget: "string"}
      - {label: "Features", name: "features", widget: "text"}
      - {label: "Tech stack", name: "techStack", widget: "text"}



