backend:
  name: git-gateway
  branch: master

media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: djimngd9g
    api_key: 354114999119245

collections:
  - name: "company"
    label: "Company"
    folder: "src/__data__/company"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Id", name: "id", widget: "number"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Start", name: "start", widget: "string"}
      - {label: "End", name: "end", widget: "string"}
